//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salkodev.hiddendata.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("salkodev.hiddendata.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files.
        /// </summary>
        internal static string AddFilesCaption {
            get {
                return ResourceManager.GetString("AddFilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock_secure {
            get {
                object obj = ResourceManager.GetObject("lock-secure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        internal static string OpenFileCaption {
            get {
                return ResourceManager.GetString("OpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open any file (where you want to save hidden data).
        /// </summary>
        internal static string OpenImageFileDescr {
            get {
                return ResourceManager.GetString("OpenImageFileDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source file.
        /// </summary>
        internal static string OpenSourceImageFileCaption {
            get {
                return ResourceManager.GetString("OpenSourceImageFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open work file first.
        /// </summary>
        internal static string OpenWorkImageFileFirst {
            get {
                return ResourceManager.GetString("OpenWorkImageFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        internal static string SelectFileCaption {
            get {
                return ResourceManager.GetString("SelectFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only one file to open it for viewing.
        /// </summary>
        internal static string SelectOnlyOneFileToOpen {
            get {
                return ResourceManager.GetString("SelectOnlyOneFileToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add at least file.
        /// </summary>
        internal static string YouNeedToAddAtLeastFile {
            get {
                return ResourceManager.GetString("YouNeedToAddAtLeastFile", resourceCulture);
            }
        }
    }
}
